/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pendaftaran pengguna baru (Lokal Email & Password) */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk menggunakan Email dan Password lokal */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentikasi Single Sign-On via Google OAuth */
        post: operations["loginGoogleOAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mengambil profil pengguna yang sedang login */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mengambil daftar riwayat batch kalibrasi pengguna */
        get: operations["listCalibrationBatches"];
        put?: never;
        /**
         * Validasi, perhitungan, dan penyimpanan batch pengujian kalibrasi
         * @description Menerima batch pengujian lengkap (standar dan sampel multi-analit).
         *     Backend memvalidasi perhitungan metrologi via `@valid-ex/math`, mengevaluasi kriteria QC
         *     (korelasi Pearson, CCV drift, RPD duplo, recovery spike), dan menyimpan data secara ACID.
         *     Sesuai Invariant D4 & ADR-0005, jika QC gagal, data tetap disimpan dengan status INVALID_QC (Soft-Flag).
         */
        post: operations["createCalibrationBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mengambil detail lengkap 1 batch pengujian dan hasil kuantifikasinya */
        get: operations["getCalibrationBatchById"];
        put?: never;
        post?: never;
        /** Menghapus batch kalibrasi */
        delete: operations["deleteCalibrationBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibrations/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mengunduh lembar kerja spreadsheet audit trail (.xlsx)
         * @description Menghasilkan file Excel biner (.xlsx) berisi formula native Excel (=SLOPE, =INTERCEPT, =IF)
         *     dan tabel terstruktur. Semua string pengguna disanitasi dari formula injection (Anti-CWE-1236).
         */
        get: operations["exportCalibrationExcel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qc-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mengambil daftar profil kriteria QC milik pengguna */
        get: operations["listQcProfiles"];
        put?: never;
        /** Membuat profil kriteria QC baru (versi berikutnya bila nama sama) */
        post: operations["createQcProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qc-profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mengambil satu profil kriteria QC (versi terbaru) */
        get: operations["getQcProfileById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @example analis@lab.com
             */
            email: string;
            /**
             * Format: password
             * @example SuperSecureLab123!
             */
            password: string;
            /** @example Zidan */
            name: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example analis@lab.com
             */
            email: string;
            /**
             * Format: password
             * @example SuperSecureLab123!
             */
            password: string;
        };
        GoogleAuthRequest: {
            /**
             * @description Google OAuth Identity Token
             * @example eyJhbGciOiJSUzI1NiIs...
             */
            idToken: string;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            avatarUrl?: string | null;
            /** @enum {string} */
            authProvider: "local" | "google";
            /** Format: date-time */
            createdAt: string;
        };
        AuthResponse: {
            /** @description JWT Access Token */
            accessToken: string;
            /** @default Bearer */
            tokenType: string;
            user: components["schemas"]["UserProfile"];
        };
        /**
         * @example ICP-MS
         * @enum {string}
         */
        InstrumentType: "ICP-MS" | "ICP-OES" | "AAS" | "HPLC" | "GC-MS";
        /**
         * @description Menentukan SEMANTIK `SampleRowInput.readings` (bukan standar kalibrasi):
         *     - raw_signal: readings berisi detector response (cps/intensitas/luas area). C_sample diperoleh via inverse regression (y - c) / m.
         *     - in_vial_concentration: readings berisi konsentrasi in-vial hasil software alat (mis. Qtegra). C_sample dipakai langsung.
         *
         *     CATATAN PENTING: deret standar kalibrasi WAJIB selalu menyertakan `signal` (c/s) pada kedua mode,
         *     karena kurva OLS y = mx + c hanya dapat dibangun dari pasangan (konsentrasi nominal, respon detektor).
         * @example in_vial_concentration
         * @enum {string}
         */
        InputMode: "raw_signal" | "in_vial_concentration";
        MetrologyUnits: {
            /**
             * @description Satuan konsentrasi larutan di vial (ppb = ug/L, ppm = mg/L, ppt = ng/L)
             * @example ppb
             * @enum {string}
             */
            solutionConcUnit: "ppb" | "ppm" | "ppt";
            /**
             * @description Satuan hasil akhir kuantifikasi sampel padatan
             * @default mg/kg
             * @example mg/kg
             * @enum {string}
             */
            solidResultUnit: "mg/kg" | "ug/kg" | "percent";
            /**
             * @default g
             * @example g
             * @enum {string}
             */
            weightUnit: "g" | "mg";
            /**
             * @default mL
             * @example mL
             * @enum {string}
             */
            volumeUnit: "mL" | "L";
            /**
             * @description Satuan pembacaan respon detektor. WAJIB, karena deret standar selalu menggunakan signal pada kedua inputMode.
             * @example cps
             * @enum {string}
             */
            signalUnit: "cps" | "intensity" | "peak_area";
        };
        /**
         * @description - sample: sampel uji rutin lab
         *     - blank_method: blanko metode preparasi asam (untuk koreksi C_blank)
         *     - ccv: continuing calibration verification (larutan standar kontrol)
         *     - spike: sampel yang ditambahkan larutan standar spike (matrix spike)
         *     - duplicate: sampel ulangan duplo untuk verifikasi presisi RPD
         * @example sample
         * @enum {string}
         */
        SampleType: "sample" | "blank_method" | "ccv" | "spike" | "duplicate";
        /**
         * @description - NOT_DETECTED: C_net <= 0 atau C_net < LOD (dilaporkan 'ND')
         *     - QUALITATIVE_ONLY: LOD <= C_net < LOQ (dilaporkan '< [LOQ_metode]')
         *     - VALID_QUANTIFICATION: C_net >= LOQ (dilaporkan angka numerik mg/kg)
         * @example VALID_QUANTIFICATION
         * @enum {string}
         */
        DetectionZone: "NOT_DETECTED" | "QUALITATIVE_ONLY" | "VALID_QUANTIFICATION";
        /**
         * @example PASSED
         * @enum {string}
         */
        QCStatus: "PASSED" | "INVALID_QC";
        RecoveryBand: {
            /**
             * @description Batas ATAS band (eksklusif) dalam solutionConcUnit. null = catch-all (tak hingga). Band terakhir WAJIB null.
             * @example 100
             */
            maxConc: number | null;
            /**
             * @description % recovery minimum yang diterima pada band ini
             * @example 90
             */
            minRecovery: number;
            /**
             * @description % recovery maksimum yang diterima pada band ini
             * @example 110
             */
            maxRecovery: number;
        };
        RpdBand: {
            /**
             * @description Batas ATAS band (eksklusif) dalam solutionConcUnit. null = catch-all (tak hingga). Band terakhir WAJIB null.
             * @example 10
             */
            maxConc: number | null;
            /**
             * @description % RPD maksimum yang diterima pada band ini
             * @example 25
             */
            maxRpd: number;
        };
        AnalyteCriteria: {
            ccv: {
                /** @description Band terurut menaik; batas kontigu & non-overlap; elemen terakhir maxConc wajib null. */
                bands: components["schemas"]["RecoveryBand"][];
            };
            spike: {
                bands: components["schemas"]["RecoveryBand"][];
            };
            duplicate: {
                bands: components["schemas"]["RpdBand"][];
            };
        };
        /**
         * @description Profil kriteria QC yang immutable & ber-versi. Mengubah angka = membuat versi baru.
         *     Batch WAJIB merujuk profil ini; tidak ada override per batch.
         */
        QCCriteriaProfile: {
            /** Format: uuid */
            id: string;
            /** @example QC Criteria Check — SOP Lab */
            name: string;
            /**
             * @description Sitasi sumber kriteria (nomor SOP / metode regulatori). Wajib untuk jejak audit.
             * @example Lab SOP QC CRITERIA CHECK
             */
            methodRef: string;
            /** @example 1 */
            version: number;
            /**
             * Format: date
             * @example 2026-09-27
             */
            effectiveDate: string;
            /**
             * @description Satuan batas band. Wajib bila terdapat band dengan maxConc finit; boleh null bila seluruh profil flat.
             * @enum {string|null}
             */
            solutionConcUnit?: "ppb" | "ppm" | "ppt" | null;
            linearity: {
                /**
                 * @description Batas minimal korelasi Pearson (global per profil, bukan per band)
                 * @example 0.995
                 */
                minR: number;
            };
            /** @description WAJIB memuat entri untuk setiap analit yang dipakai batch (tanpa fallback implisit). */
            analytes: {
                [key: string]: components["schemas"]["AnalyteCriteria"];
            };
        };
        /** @description Payload pembuatan profil baru (server yang menetapkan id & version). */
        QCCriteriaProfileInput: {
            name: string;
            methodRef: string;
            /** Format: date */
            effectiveDate: string;
            /** @enum {string|null} */
            solutionConcUnit?: "ppb" | "ppm" | "ppt" | null;
            linearity: {
                minR: number;
            };
            analytes: {
                [key: string]: components["schemas"]["AnalyteCriteria"];
            };
        };
        QcProfileRef: {
            /** Format: uuid */
            id: string;
            version: number;
        };
        /** @description Jejak audit: kriteria persis yang diterapkan pada evaluasi ini. */
        AppliedCriteria: {
            /** @description Nilai konsentrasi yang dipakai untuk memilih band (CCV=expectedConc, spike=spikeAdded, duplo=mean C_net). */
            testValue?: number | null;
            bandMaxConc?: number | null;
            min?: number | null;
            max?: number | null;
        };
        StandardPointReading: {
            /**
             * @description Konsentrasi nominal larutan standar (dalam solutionConcUnit)
             * @example 10
             */
            nominalConc: number;
            /**
             * @description Pembacaan respon detektor (c/s) untuk titik standar ini. WAJIB pada kedua inputMode (sumber kurva kalibrasi).
             * @example 12500
             */
            signal: number;
        };
        StandardRowInput: {
            /** @example Std 1 */
            standardName: string;
            /**
             * @description Map nama analit -> pembacaan standar
             * @example {
             *       "Al": {
             *         "nominalConc": 10,
             *         "signal": 1500
             *       },
             *       "Pb": {
             *         "nominalConc": 1,
             *         "signal": 240
             *       },
             *       "Cd": {
             *         "nominalConc": 0.5,
             *         "signal": 95
             *       }
             *     }
             */
            readings: {
                [key: string]: components["schemas"]["StandardPointReading"];
            };
        };
        SampleRowInput: {
            /**
             * @description ID atau label sampel
             * @example 1111 (1)
             */
            sampleId: string;
            sampleType: components["schemas"]["SampleType"];
            /**
             * @description ID sampel acuan (wajib untuk sampleType: duplicate dan spike)
             * @example 1111 (1)
             */
            parentSampleId?: string | null;
            /**
             * @description Konsentrasi standar spike yang ditambahkan ke larutan (dalam solutionConcUnit)
             * @example {
             *       "Al": 20,
             *       "Pb": 2
             *     }
             */
            spikeAdded?: {
                [key: string]: number;
            } | null;
            /**
             * @description Konsentrasi target teoritis larutan kontrol / CCV (dalam solutionConcUnit)
             * @example {
             *       "Al": 5,
             *       "Pb": 1
             *     }
             */
            expectedConc?: {
                [key: string]: number;
            } | null;
            /**
             * @description Bobot penimbangan sampel padatan (gram)
             * @example 0.2014
             */
            weight: number;
            /**
             * @description Volume akhir labu ukur preparasi (mL)
             * @example 50
             */
            volume: number;
            /**
             * @description Faktor pengenceran (Dilution Factor)
             * @default 1
             * @example 1
             */
            df: number;
            /**
             * @description Map nama analit -> nilai pembacaan alat (sinyal cps atau konsentrasi terhitung di vial)
             * @example {
             *       "Al": 38.52,
             *       "Pb": 1.16,
             *       "Cd": 0.031
             *     }
             */
            readings: {
                [key: string]: number;
            };
        };
        CalibrationBatchRequest: {
            /** @example Pengujian ICP-MS Batch Biskuit Gandum */
            title: string;
            instrument: components["schemas"]["InstrumentType"];
            inputMode: components["schemas"]["InputMode"];
            units: components["schemas"]["MetrologyUnits"];
            /**
             * Format: uuid
             * @description Referensi profil kriteria QC ber-versi. Tidak ada override kriteria per batch.
             * @example 3f8a1c2e-9b7d-4bad-9bdd-2b0d7b3dcb6d
             */
            qcProfileId: string;
            /**
             * @example [
             *       "Al",
             *       "Pb",
             *       "Cd",
             *       "As",
             *       "Hg"
             *     ]
             */
            analytes: string[];
            standards: components["schemas"]["StandardRowInput"][];
            samples: components["schemas"]["SampleRowInput"][];
        };
        AnalyteCurveMetrics: {
            /** @example 240.5 */
            slope: number;
            /** @example 1.2 */
            intercept: number;
            /**
             * @description Koefisien korelasi Pearson
             * @example 0.9998
             */
            r: number;
            /**
             * @description Koefisien determinasi R²
             * @example 0.9996
             */
            rSquared: number;
            /**
             * @description Standar deviasi residual regresi s_{y/x}
             * @example 0.045
             */
            syx: number;
            /**
             * @description Limit of Detection instrumen di vial (dalam solutionConcUnit) = 3 * syx / slope
             * @example 0.005
             */
            lodInstrument: number;
            /**
             * @description Limit of Quantification instrumen di vial (dalam solutionConcUnit) = 10 * syx / slope
             * @example 0.015
             */
            loqInstrument: number;
        };
        AnalyteSampleResult: {
            /**
             * @description Pembacaan konsentrasi di vial sebelum koreksi blanko (dalam solutionConcUnit)
             * @example 1.16
             */
            cRaw: number;
            /**
             * @description Konsentrasi larutan bersih setelah koreksi blanko (C_sample - C_blank)
             * @example 1.15
             */
            cNet: number;
            /**
             * @description Hasil kuantifikasi padatan (dalam solidResultUnit). NULL jika cNet < LOQ.
             * @example 0.28678
             */
            concSolid?: number | null;
            detectionZone: components["schemas"]["DetectionZone"];
            /**
             * @description Format pelaporan resmi ISO 17025 ('ND', '< [LOQ_metode]', atau angka desimal)
             * @example 0.287 mg/kg
             */
            reportedValue: string;
            /**
             * @description LOD metode PADA SAMPEL INI (solidResultUnit), dihitung dari W/V/dF sampel ini
             * @example 0.00125
             */
            lodMethod: number;
            /**
             * @description LOQ metode PADA SAMPEL INI (solidResultUnit), dipakai pada string '< [LOQ_metode]'
             * @example 0.00375
             */
            loqMethod: number;
            /**
             * @description % Relative Percent Difference jika baris ini adalah duplo. Bernilai null bila rata-rata pasangan <= 0 (undefined).
             * @example 1.72
             */
            rpd?: number | null;
            /**
             * @description % Recovery jika baris ini adalah matrix spike
             * @example 99
             */
            spikeRecovery?: number | null;
            /**
             * @description % Recovery jika baris ini adalah CCV / larutan kontrol
             * @example 101.2
             */
            ccvRecovery?: number | null;
        };
        EvaluatedSampleRow: {
            /** @example 1111 (1) */
            sampleId: string;
            sampleType: components["schemas"]["SampleType"];
            /** @example null */
            parentSampleId?: string | null;
            /** @example 0.2014 */
            weight: number;
            /** @example 50 */
            volume: number;
            /** @example 1 */
            df: number;
            /** @description Map nama analit -> hasil evaluasi metrologi */
            analytes: {
                [key: string]: components["schemas"]["AnalyteSampleResult"];
            };
        };
        QCViolationRecord: {
            /**
             * @example CCV_RECOVERY
             * @enum {string}
             */
            rule: "LINEARITY_R" | "CCV_RECOVERY" | "SPIKE_RECOVERY" | "DUPLICATE_RPD";
            /** @example Pb */
            analyte: string;
            /** @example CCV-Mid */
            sampleId?: string | null;
            /** @example 90.0% - 110.0% */
            expected: string;
            /** @example 115.4% */
            actual: string;
            /** @example Continuing Calibration Verification (CCV) melebihi batas drift toleransi 10% */
            message: string;
            /**
             * @description Versi profil kriteria yang diterapkan saat pelanggaran ini terjadi (jejak audit).
             * @example 1
             */
            profileVersion: number;
            appliedCriteria: components["schemas"]["AppliedCriteria"];
        };
        CalibrationBatchResponse: {
            /** Format: uuid */
            id: string;
            title: string;
            instrument: components["schemas"]["InstrumentType"];
            inputMode: components["schemas"]["InputMode"];
            units: components["schemas"]["MetrologyUnits"];
            qcProfileRef: components["schemas"]["QcProfileRef"];
            qcProfileSnapshot: components["schemas"]["QCCriteriaProfile"] & unknown;
            qcStatus: components["schemas"]["QCStatus"];
            qcViolations: components["schemas"]["QCViolationRecord"][];
            /** @description Map nama analit -> ringkasan metrologi kurva regresi */
            analytesSummary: {
                [key: string]: components["schemas"]["AnalyteCurveMetrics"];
            };
            evaluatedSamples: components["schemas"]["EvaluatedSampleRow"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CalibrationListResponse: {
            data: {
                /** Format: uuid */
                id: string;
                title: string;
                instrument: components["schemas"]["InstrumentType"];
                qcStatus: components["schemas"]["QCStatus"];
                /** Format: date-time */
                createdAt: string;
            }[];
            meta: {
                page: number;
                limit: number;
                totalItems: number;
                totalPages: number;
            };
        };
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example Permintaan tidak dapat diproses. */
            message: string;
            /**
             * @example [
             *       "Deret kalibrasi wajib memiliki minimal 5 konsentrasi non-zero."
             *     ]
             */
            details?: string[];
        };
    };
    responses: {
        /** @description Request payload tidak valid atau gagal validasi skema */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token autentikasi hilang, kedaluwarsa, atau tidak valid */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Sumber daya yang diminta tidak ditemukan */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description UUID unik batch kalibrasi */
        CalibrationIdParam: string;
        /** @description UUID unik profil kriteria QC */
        QcProfileIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Pengguna berhasil didaftarkan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            /** @description Email sudah terdaftar */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login berhasil, mengembalikan JWT token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Akun terdaftar via OAuth (penolakan login manual tanpa password) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Kredensial tidak valid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginGoogleOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Autentikasi Google berhasil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Token Google OAuth tidak valid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil pengguna berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    listCalibrationBatches: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                instrument?: components["schemas"]["InstrumentType"];
                qcStatus?: components["schemas"]["QCStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar batch kalibrasi berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createCalibrationBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationBatchRequest"];
            };
        };
        responses: {
            /** @description Batch kalibrasi berhasil diproses dan disimpan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationBatchResponse"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            /** @description Pelanggaran batas metrologi fatal (misal deret standar non-zero < 5 titik) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCalibrationBatchById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID unik batch kalibrasi */
                id: components["parameters"]["CalibrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail batch kalibrasi ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationBatchResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    deleteCalibrationBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID unik batch kalibrasi */
                id: components["parameters"]["CalibrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Batch kalibrasi berhasil dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    exportCalibrationExcel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID unik batch kalibrasi */
                id: components["parameters"]["CalibrationIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File spreadsheet binary hasil olah data (.xlsx) */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
    listQcProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar profil berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCCriteriaProfile"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
        };
    };
    createQcProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QCCriteriaProfileInput"];
            };
        };
        responses: {
            /** @description Profil berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCCriteriaProfile"];
                };
            };
            400: components["responses"]["BadRequestError"];
            401: components["responses"]["UnauthorizedError"];
            /** @description Profil tidak valid (band tidak kontigu, tidak ada catch-all, atau analit duplikat) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getQcProfileById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID unik profil kriteria QC */
                id: components["parameters"]["QcProfileIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil ditemukan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QCCriteriaProfile"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
        };
    };
}
